// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdmvgxtzrrfqbjwkxdfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbXZneHR6cnJmcWJqd2t4ZGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2OTExODIsImV4cCI6MjA1NDI2NzE4Mn0.FcmIjdyLMScIcdF1p1CMJl9lWF6oZbG6hDXPrfB45AE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);